spring:
  application:
    name: topicals

  datasource:
    url: jdbc:mariadb://localhost:3306/topicals
    username: ${TOPICALS_DB_USER}
    password: ${TOPICALS_DB_PWD}
    driver-class-name: org.mariadb.jdbc.Driver
  
  sql:
    init:
      mode: never
      schema-locations: optional:classpath:/db_init/schema.sql
      data-locations: optional:classpath:/db_init/data.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect