spring:
  application:
    name: topicals

  datasource:
    url: jdbc:mysql://localhost:3306/topicals_db
    username: ${TOPICALS_DB_USER}
    password: ${TOPICALS_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  sql:
    init:
      mode: never
      schema-locations: optional:classpath:/db_init/schema.sql
      data-locations: optional:classpath:/db_init/data.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: ${TOPICALS_SECRET}
      expiration: ${TOPICALS_JWT_EXP}
      refresh-token:
        expiration: {TOPICALS_REFRESH_EXP}
